export const INCREMENT_DAY = 'INCREMENT_DAY'
export const DECREMENT_DAY = 'DECREMENT_DAY'

export const REQUEST_INFO_USER = 'REQUEST_INFO_USER'
export const RECIVE_INFO_USER = 'RECIVE_INFO_USER'
export const FAIL_INFO_USER = 'FAIL_INFO_USER'

export const LOG_OUT = 'LOG_OUT'
